contact_links:
  - name: 🤔 Вопросы и обсуждения
    url: https://github.com/VKCOM/VKUI/discussions
    about: Если у вас есть вопросы по работе библиотеки или хочется обсудить/предложить доработки, откройте обсуждение.
